### ISSUE TITLE
Enable video sound/playback controls on click?

### ISSUE THREAD

**Issue by brookschambers** [brookschambers/brookschambers.com#17]
This is more of a question than an issue, but I'm wondering if it'd be possible to enable things like sound and playback controls for videos on click/tap.

**Comment by drwpow** [comment]
Yeah we can add controls to videos! For the autoplay, it’s a requirement that they be muted in order for them to play. I imagined a big wall of “play” buttons wouldn’t be manually interacted with, but agree that on an individual basis someone may want to actually watch a certain video. Will throw up a preview PR to play with and you can give me feedback!
