### ISSUE TITLE
Fingernails rendering weird

### ISSUE THREAD

**Issue by brookschambers** [brookschambers/brookschambers.com#24]
In the "Dashboards aren't enough to understand churn" graphic in the mode section, the fingernails have some weird black artifacts. 
<img width="371" alt="CleanShot 2023-08-10 at 11 11 55@2x" src="https://github.com/brookschambers/brookschambers.com/assets/16626711/447d1d0b-1ae1-46a9-946d-5ee5b6db2077">

**Comment by drwpow** [comment]
When I read the title I thought “No, Brooks, they’re called _thumbnails_.”

You said the right thing

**Comment by drwpow** [comment]
GitHub’s [image comparison tools](https://github.com/brookschambers/brookschambers.com/pull/30/files) are soo goooooood

![CleanShot 2023-08-16 at 09 05 24](https://github.com/brookschambers/brookschambers.com/assets/1369770/de33a427-2c96-47fa-8ad8-b1b03ee2a98e)
